### ISSUE TITLE
Auto-Detect "if you are using 'prop-types' model"

### ISSUE THREAD

**Issue by ryanbrainard** [dpzxsm/ReactPropTypes-Plugin#1]
Instead of making the user check "if you are using 'prop-types' model" every time, it would be nice if this could just be auto-detected by the plugin inspecting the file. 

If this is difficult to do, an alternative would be just remembering the setting from the last time. Having to check this every time is pretty annoying.

**Comment by dpzxsm** [comment]
@ryanbrainard  
The purpose of this checkBox is to help you auto import modules, I forgot about it. But if your JS File 
has imported React.PropTypes or prop-types , I will do nothing. So don’t worry , just ignore it.
But that's a good idea , I will fix it in the next version, if your JS file contain "import PropTypes from 'prop-types'", I will auto check it.

**Comment by ryanbrainard** [comment]
Instead of having both a checkbox and select field, it would probably be better to have just one select:

Auto-Import: [ Disabled | ES6 | ES7 ]

That will be simplifier and clearer to the user what it does. The current “if you are using ...” label is a bit confusing they way it’s worded. 

Thanka for working on the fix!

**Comment by dpzxsm** [comment]
@ryanbrainard This is a very good proposal. Thank you very much
