### ISSUE TITLE
My component is not detected

### ISSUE THREAD

**Issue by paour** [dpzxsm/ReactPropTypes-Plugin#2]
When I select the name of my stateless component and trigger the plugin, I get an alert claiming `The selected text is not a valid React Component` (with a type, it's `valid`, not `vaild`).

My component is valid, however, but what may be throwing the plugin off is that it's wrapped in a HOC (`withStyles`).

![galleryheader_-_collector-web_-____sirupdev_sirup_collector-web_](https://user-images.githubusercontent.com/90963/34213573-dc772306-e59f-11e7-8306-c38eff2d853e.png)

[Full code](https://gist.github.com/d49e64b7d3992f42f1e7214fcf8f14be)

**Comment by sponia-joker** [comment]
i hava the same problem.i guess the HOC was't supported

**Comment by sponia-joker** [comment]
@dpzxsm would you please fix the bug.thanks

**Comment by dpzxsm** [comment]
@paour  @sponia-joker Oh！It happens when your stateless component without 'export'. It's very busy now. I don't guarantee that I can solve this problem soon, maybe a week.Now You can change the arrowhead function for the time being

**Comment by dpzxsm** [comment]
Fixed #2 in the version 1.0.6

**Comment by dpzxsm** [comment]
Close the issue because has fixed in the version 1.0.6

**Comment by sponia-joker** [comment]
it's perfect
