### ISSUE TITLE
Also handle defaultProp

### ISSUE THREAD

**Issue by paour** [dpzxsm/ReactPropTypes-Plugin#3]
Would you consider adding support for defaultProps in the dialog, so that we can in one go generate the `propTypes` and `defaultProps`?

**Comment by dpzxsm** [comment]
@paour Of course, it's already in the plan. But I haven't thought about how to design UI about it. Maybe I should replace  the "describe" with "defaultValue" in the dialog. By the way, I also want to support PropTypes.shap, do you have any good idea about UI ?

**Comment by paour** [comment]
Yes, replacing describe with defaultValue sounds like a great idea, or you could add another column.

Regarding shapes, could you add another action button that opens a similar dialog to the current one to define the fields in the object?

**Comment by dpzxsm** [comment]
@paour Add another column look likes too complex , I don't want to do this. Now it seems the "describe" column is useless, maybe I should replace it to "defaultValue".

It sounds like a good idea to open a new dialog, I am in favor of this opinion.I will add this feature in the next version, which is expected to be released next week.

Thank you very much.

**Comment by paour** [comment]
Great, thank you!
