### ISSUE TITLE
Semi-colons not inserted with imports or propTypes block

### ISSUE THREAD

**Issue by arcos** [dpzxsm/ReactPropTypes-Plugin#4]
When you add PropTypes to a component there are no semi-colons after the auto-added imports and after the PropTypes block itself:

```javascript
import PropTypes from 'prop-types'

//etc

PreferenceOptions.propTypes = {
  URL: PropTypes.string.isRequired,
  thing: PropTypes.array,
  messages: PropTypes.object.isRequired,
  options: PropTypes.array.isRequired  
}

```

**Comment by dpzxsm** [comment]
Now, the generated code's style is default.  Someone like no semi-colons after every statement, but others don't. I know not everyone likes the style of code generation.  In the next version, I will provide a setting page so you can custom your code's style, include semi-colons 、indent and other option. I'm not sure how much time it will take, wait when I'm free.  @arcos

**Comment by dpzxsm** [comment]
@arcos You can choose whether or not you need semi-colons in Setting
