### ISSUE TITLE
Add functionality for functional components

### ISSUE THREAD

**Issue by ecbrodie** [dpzxsm/ReactPropTypes-Plugin#7]
It doesn't look like this extension supports functional components, only class components. It would be very nice to support that, especially with functional components becoming more popular in general (React framework optimizations for functional component performance, libraries like `recompose` making it possible to add lifecycle methods to functional components, etc).

**Comment by dpzxsm** [comment]
@ecbrodie This is a bug, it should have supported  for functional components, now it is not work ! I will fix it withIn a few days

**Comment by dpzxsm** [comment]
@ecbrodie  For the time being, you can change  the style to ES6  , like this：
![1534904405511](https://user-images.githubusercontent.com/20736977/44439174-0a1c5680-a5f5-11e8-9b24-cb93a50a750d.jpg)
It is workful.

**Comment by dpzxsm** [comment]
Thank you for bringing up this issue. I have finished repairing it. Please wait for a few days or download <a href=https://raw.githubusercontent.com/dpzxsm/ReactPropTypes-Plugin-Intellij/master/ReactPropTypes.jar>ReactPropTypes.jar</a> installation directly.

**Comment by ecbrodie** [comment]
Woa, that was fast! Thanks. I'll wait for the public release before I try it out again
